### ISSUE TITLE
Crash in version 2.6.13

### ISSUE THREAD

**Issue by nkrSmartq** [zebra-technologies/Scanner-SDK-for-Android#11]
Hi Team,

We tried updating library to latest available version on web-site. (2.6.13).
App is crashing when we move activity to background.

Please help if I'm missing something.

_**Note**: Using Zebra DS9308 scanner in SNAPI mode._

**Comment by sproctor** [comment]
This is a duplicate of #9. Look there for workarounds.

**Comment by nkrSmartq** [comment]
Thanks !!
